import enum

class FriendStatus(enum.Enum):
    ACCEPTED = 1
    PENDING = 2
    REJECTED = 3

class WebSocketRequestEvent(enum.Enum):
    SEND_MESSAGE = "SEND_MESSAGE"
    GET_MESSAGES = "GET_MESSAGES"
    CREATE_GROUP_CHAT = "CREATE_GROUP_CHAT"
    LEAVE_GROUP_CHAT = "LEAVE_GROUP_CHAT"
    GET_ROOMS = "GET_ROOMS"
    GET_ROOM_INFO = "GET_ROOM_INFO"
    GET_GROUP_CHATS = "GET_GROUP_CHATS"
    JOIN_GROUP_CHAT = "JOIN_GROUP_CHAT"
    CONFIRM_JOIN_GROUP_CHAT = "CONFIRM_JOIN_GROUP_CHAT"
    INVITE_TO_GROUP_CHAT = "INVITE_TO_GROUP_CHAT"
    GET_FRIENDS = "GET_FRIENDS"
    SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST"
    CONFIRM_SEND_FRIEND_REQUEST = "CONFIRM_SEND_FRIEND_REQUEST"
    ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST"
    REJECT_FRIEND_REQUEST = "REJECT_FRIEND_REQUEST"

class WebSocketResponseEvent(enum.Enum):
    SEND_MESSAGE = "SEND_MESSAGE"
    GET_MESSAGES = "GET_MESSAGES"
    CREATE_GROUP_CHAT = "CREATE_GROUP_CHAT"
    LEAVE_GROUP_CHAT = "LEAVE_GROUP_CHAT"
    GET_ROOMS = "GET_ROOMS"
    GET_ROOM_INFO = "GET_ROOM_INFO"
    GET_GROUP_CHATS = "GET_GROUP_CHATS"
    JOIN_GROUP_CHAT = "JOIN_GROUP_CHAT"
    CONFIRM_JOIN_GROUP_CHAT = "CONFIRM_JOIN_GROUP_CHAT"
    INVITE_TO_GROUP_CHAT = "INVITE_TO_GROUP_CHAT"
    GET_FRIENDS = "GET_FRIENDS"
    SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST"
    CONFIRM_SEND_FRIEND_REQUEST = "CONFIRM_SEND_FRIEND_REQUEST"
    ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST"
    REJECT_FRIEND_REQUEST = "REJECT_FRIEND_REQUEST"
